import type { Metadata } from "next";
import '@/styles/globals.scss';

import localFont from 'next/font/local';

import Footer from '@/components/layout/footer';
import Header from '@/components/layout/header';
import ReactQueryWrapper from '@/components/layout/ReactQueryWrapper';
import { ThemeProvider } from '@/components/theme-provider';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-svh h-full flex flex-col overflow-x-hidden`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryWrapper>
            <Header />
            <main className="container">{children}</main>
            <Footer />
          </ReactQueryWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
